package.json
src/assets/base/general.styl
src/assets/base/variables.styl
src/assets/main.styl
src/layouts/components.html

https://github.com/yandex-shri-minsk-2016/foodhub/issues/29
Добавил файл general.styl, в котором будут лежать общие для всего сайта стили, переменные и миксины для основных цветов, подключил нужные шрифты.

29_Added general.styl, general styles and color variables

---

gulpfile.js

Из-за туннеля часто падал browser-sync

Изменена конфигурация browser-sync

---

src/layouts/components.html

Данный тег запрещает браузеру масштабировать страницу

Добавлен meta для корректного отображения адаптива

---

src/assets/base/variables.styl
src/assets/components/menu_tabs/menu_tabs.html
src/assets/components/menu_tabs/menu_tabs.styl
src/layouts/components.html

Added menu tabs component

---

.gitattributes

https://github.com/yandex-shri-minsk-2016/foodhub/issues/52

Добавил файл gitattributes

---

src/assets/components/quantity-input/quantity-input.styl

#55_Исправил quantity-input

---

frontend/gulpfile.js
frontend/package.json
frontend/src/app.js
frontend/src/components/footer/footer.js
frontend/src/components/header/header.html
frontend/src/components/header/header.js
frontend/src/components/my_profile/my_profile.js
frontend/src/index.html

https://github.com/yandex-shri-minsk-2016/foodhub/issues/84,
https://github.com/yandex-shri-minsk-2016/foodhub/issues/87,
https://github.com/yandex-shri-minsk-2016/foodhub/issues/89.

Создание компонентов header, footer, my_profile.

---

server/app.js
server/controllers/authController.js
server/controllers/odersController.js
server/controllers/sessionsController.js
server/controllers/shopsController.js
server/controllers/usersController.js
server/routes/routes.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/108

Роутинг и заглушки экшенов контроллеров на сервере

---

frontend/src/app.js
frontend/src/components/session_list/session_list.html
frontend/src/components/session_list/session_list.js
frontend/src/fixtures/sessionList.js
frontend/src/views/components/components.html
frontend/src/views/components/components.js
frontend/src/views/session_list_page/session_list_page.html
frontend/src/views/session_list_page/session_list_page.js

Создание Angular компонента "session_list" 

---

frontend/src/app.js
frontend/src/components/quantity-input/quantity-input.html
frontend/src/components/quantity-input/quantity-input.js
frontend/src/components/quantity-input/quantity-input.styl
frontend/src/views/components/components.html

Ангулар компонент quantity-input

---

frontend/src/components/quantity-input/quantity-input.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/120

Исправил скоуп и рендер quantity_input

---

frontend/package.json
frontend/src/app.js
frontend/src/services/auth.js
frontend/src/services/shops.js
frontend/src/views/session_list_page/session_list_page.js

шаблон для сервисов на примере shops

---

server/app.js

middleware для разрешения конфликтов между сервером и клиентом

---

server/app.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/139

Добавил заголовок Access-Control-Allow-Methods

---

server/app.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/144

Добавил CORS заголовки

---

frontend/src/app.js
frontend/src/components/form/form.html
frontend/src/components/form/form.js
frontend/src/components/text_input/text_input.styl
frontend/src/views/components/components.html

85_Ангулар компонент form

---

server/migrations/20160427234100-create_foods_table.js
server/models/Food.js
server/package.json
server/parser/Parser.js
server/parser/PizzaTempo.js
server/seeders/20160430131316-foods.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/124
Парсер создает массив объектов вида
```
{name, description, imageUrl, price, externalFoodId, category}
```
Для парсинга требуется создать новый объект класса `PizzaTempo` и вызвать метод `getProducts`
Для наглядности можно вывести `console.log(this.products)`

Парсинг http://www.pizzatempo.by/

---

server/migrations/20160427221115-create_users_table.js
server/migrations/20160427230534-add_email_index_to_users_table.js
server/migrations/20160427231109-add_external_index_to_users_table.js
server/migrations/20160427231717-create_shops_table.js
server/migrations/20160427232811-add_name_index_to_shops_table.js
server/migrations/20160427233039-create_food_categories_table.js
server/migrations/20160427234100-create_foods_table.js
server/migrations/20160427235003-create_sessions_table.js
server/migrations/20160427235421-add_status_index_to_sessions_table.js
server/migrations/20160427235640-create_orders_table.js
server/migrations/20160428000159-create_food_orders_table.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/161

Добавил return в функции миграций базы

---

server/migrations/20160427233039-create_food_categories_table.js
server/models/FoodCategory.js
server/seeders/20160430113233-food_categories.js
server/seeders/20160430131316-foods.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/159

Добавил поле shop_id в таблицу food_categories

---

server/app.js
server/errors/errors.js
server/middleware/isAuthenticated.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/168

Добавил конструкторы кастомных ошибох и мидлвар перехватчик

---

server/controllers/sessionsController.js
server/models/FoodOrder.js
server/models/Session.js
server/models/models.js
server/routes/routes.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/154

Добавил экшена контроллера sessions, добавил связи между моделями

---

server/controllers/ordersController.js
server/errors/errors.js
server/middleware/validators.js
server/migrations/20160428000159-create_food_orders_table.js
server/models/FoodOrder.js
server/models/Order.js
server/models/models.js
server/routes/routes.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/154

Добавил экшены контроллера orders, добавил валидации модели FoodOrders и Orders, исправил несколько багов

---

server/app.js
server/controllers/ordersController.js
server/controllers/sessionsController.js
server/controllers/shopsController.js
server/controllers/usersController.js
server/middleware/stubAuth.js
server/migrations/20160510012515-rename_is_paid_column.js
server/models/Order.js
server/seeders/20160430133543-orders.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/179

Подрефакторил, исправил баги, добавил мидлвар stubAuth, переименовал поле is_payed в is_paid.

---

frontend/src/app.js
frontend/src/components/form/form.html
frontend/src/components/session_info/session_info.js
frontend/src/components/text_input/text_input.html
frontend/src/components/text_input/text_input.js
frontend/src/views/last_page/last_page.html
frontend/src/views/last_page/last_page.js
server/app.js
server/controllers/shopsController.js

Страница подтверждения

---

frontend/package.json
frontend/src/app.js
frontend/src/views/session_list_page/session_list_page.js

Исправление замечаний по ПР: #181

---

frontend/src/components/base/general.styl
frontend/src/components/cart/cart.html
frontend/src/components/cart/cart.js
frontend/src/components/cart/cart.styl
frontend/src/components/form/form.html
frontend/src/components/form/form.styl
frontend/src/components/quantity-input/quantity-input.js
frontend/src/components/text_input/text_input.html
frontend/src/components/text_input/text_input.styl
frontend/src/views/session_page/session_page.styl
frontend/src/views/session_page/session_page_food/session_page_food.html
frontend/src/views/session_page/session_page_food/session_page_food.js
frontend/src/views/session_page/session_page_users/session_page_users.html
frontend/src/views/session_page/session_page_users/session_page_users.js

1. Сделал сообщение, если юзер пытается отправить пустую корзину
2. Исправил отображение юзеров в сессии, если нету в сессии нету ни одного заказа
3. Исправил кнопки в корзине

Контроль над ошибками ввода

---

server/package.json
server/parser/script.js

https://github.com/yandex-shri-minsk-2016/foodhub/issues/158

Привязка магазинов, обернуто в cron

---

frontend/src/views/last_page/last_page.js
frontend/src/views/session_page/session_page_food/session_page_food.js
frontend/src/views/session_page/session_page_users/session_page_users.js

Прикрутил moment.js вместо filter

---

frontend/src/components/session_info/session_info.styl
frontend/src/components/session_list/session_list.html
frontend/src/components/session_list/session_list.styl
frontend/src/components/text_input/text_input.styl

Поправил стиль session_info; правка отображения оставшегося времени
